# Generated by Django 3.1.7 on 2021-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210401_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_goals',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
