# Generated by Django 3.1.7 on 2021-04-11 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
