# Generated by Django 3.1.7 on 2021-04-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_signup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('is_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_following', to='profiles.userprofile')),
            ],
        ),
    ]
