# Generated by Django 3.1.7 on 2021-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210414_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detault_billing_email',
            field=models.CharField(default='test@test.com', max_length=64),
            preserve_default=False,
        ),
    ]
