# Generated by Django 3.1.7 on 2021-04-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userprofile_detault_billing_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='detault_billing_email',
            new_name='default_billing_email',
        ),
    ]
