# Generated by Django 3.1.7 on 2021-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_auto_20210308_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttracker',
            name='workout',
            field=models.JSONField(blank=True),
        ),
    ]
