# Generated by Django 3.1.7 on 2021-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0006_auto_20210325_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttracker',
            name='workout_id',
        ),
    ]
