# Generated by Django 3.1.7 on 2021-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0007_remove_workouttracker_workout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttracker',
            name='session_average_rpe',
            field=models.FloatField(default=8.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='session_reps',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='session_volume',
            field=models.FloatField(default=4500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workouttracker',
            name='workout',
            field=models.JSONField(),
        ),
    ]
