# Generated by Django 3.1.7 on 2021-04-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210418_1202'),
        ('workout_tracker', '0009_workouttracker_session_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=1000)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='profiles.userprofile')),
                ('target_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_workout', to='profiles.userprofile')),
            ],
        ),
    ]
