# Generated by Django 3.1.7 on 2021-04-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0010_workoutcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutcomments',
            name='target_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_workout', to='workout_tracker.workouttracker'),
        ),
    ]
