# Generated by Django 3.1.7 on 2021-04-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210418_1202'),
        ('workout_tracker', '0011_auto_20210419_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now_add=True)),
                ('like_status', models.BooleanField(default=True)),
                ('liked_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_workout', to='workout_tracker.workouttracker')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='profiles.userprofile')),
            ],
        ),
    ]
