# Generated by Django 3.1.7 on 2021-04-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0012_workoutlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlikes',
            name='like_status',
        ),
    ]
